steps:

# These bits would install via Provisionator normally, so try
# to keep them in sync. Ideally we'll be able to run Prov in
# VSTS+YAML like we do for our "big builds".

- task: DotNetCoreInstaller@0
  inputs:
    version: 2.1.301
  displayName: Install .NET Core

- script: |
    mkdir -p _build/provisionator
    cat > _build/provisionator/InstallProvisionator.csproj <<EOF
    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>netcoreapp2.1</TargetFramework>
        <RestorePackagesPath>.</RestorePackagesPath>
        <RestoreProjectStyle>DotnetToolReference</RestoreProjectStyle>
        <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
        <RestoreFallbackFolders>clear</RestoreFallbackFolders>
        <RestoreAdditionalProjectFallbackFolders></RestoreAdditionalProjectFallbackFolders>
        <RestoreAdditionalProjectFallbackFoldersExcludes></RestoreAdditionalProjectFallbackFoldersExcludes>
        <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
      </PropertyGroup>
      <ItemGroup>
        <PackageReference Include="Xamarin.Provisionator" Version="*" />
      </ItemGroup>
    </Project>
    EOF
  displayName: Generate Provisionator Install Project

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '_build/provisionator/InstallProvisionator.csproj'
    vstsFeed: '5381e851-af0c-42dd-9383-9e0929b5c678'
    includeNuGetOrg: false
    noCache: true
    restoreDirectory: '_build/provisionator/packages'
  displayName: Restore Provisionator

- script: 'find _build/provisionator/packages && exit 1'
  displayName: Show all files

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: 'install -g --add-source _build/provisionator/packages/ Xamarin.Provisionator'
  displayName: Install Provisionator

- script: 'find ~/.dotnet/tools && exit 1'
  displayName: Show all files

- script: |
    MONO_VERSION=5.12.0.273
    MONO_PACKAGE="MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.universal.pkg"
    curl -LO "https://dl.xamarin.com/MonoFrameworkMDK/Macx86/${MONO_PACKAGE}"
    sudo installer -target / -pkg "${MONO_PACKAGE}"
    sudo build/select-mono.sh latest
  condition: and(succeeded(), eq(variables['agent.os'], 'darwin'))
  displayName: Install Mono

- script: provisionator
  displayName: Run Provisionator

- task: NodeTool@0
  inputs:
    versionSpec: 8.x
  displayName: Install Node.js

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: 4.6.2
  displayName: Install NuGet CLI

- script: npm install -g yarn
  displayName: Install Yarn

# This script runs both via bash (macOS/Linux) and cmd (Windows).
# Keep it both valid bash and batch or break it out conditionally.
- script: |
    echo System Environment
    set
    echo .NET Core Info
    dotnet --info
  displayName: Dump Environment

- task: MSBuild@1
  inputs:
    solution: build.proj
    configuration: '$(msbuild.configuration)'
    msbuildArguments: '/t:Restore /p:Profile=$(msbuild.buildProfile)'
  displayName: Restore

- task: MSBuild@1
  inputs:
    solution: build.proj
    msbuildArguments: '/t:Build'
  displayName: Build

- task: MSBuild@1
  inputs:
    solution: build.proj
    msbuildArguments: '/t:Package'
  displayName: Package

- task: MSBuild@1
  inputs:
    solution: build.proj
    msbuildArguments: '/t:ArchiveSymbolFiles'
  displayName: Archive Symbol Files

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '_artifacts'
    ArtifactName: Artifacts
    publishLocation: Container
  displayName: Publish Artifacts

- task: MSBuild@1
  inputs:
    solution: build.proj
    msbuildArguments: '/t:Test'
  displayName: Run xUnit Tests

- task: PublishTestResults@2
  inputs:
    testRunner: XUnit
    testResultsFiles: '**/*.Tests.xml'
  displayName: Publish xUnit Test Results