#!/bin/bash

set -ex

LEGACY_XS_ADDIN_INSTALL="${DSTROOT}${HOME#/*}/Library/Application Support/XamarinStudio-6.0/LocalInstall/Addins"
rm -rf "$LEGACY_XS_ADDIN_INSTALL/Xamarin.Inspector"
rm -rf "$LEGACY_XS_ADDIN_INSTALL/Xamarin.Interactive"

LEGACY_CLI_SCRIPT_PATH="${DSTROOT}usr/local/bin/workbook"
rm -f "$LEGACY_CLI_SCRIPT_PATH"
if [ -f ~/.zshrc ]; then
    echo -n "\nexport PATH="${DSTROOT}Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin" >> ~/.zshrc
elif [ -f ~/.profile ]; then
        echo -n "\nexport PATH="${DSTROOT}Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin" >> ~/.profile
else; then
        echo 'Cannot find a shell initialization file! Please add this line to startup script in order to setup the path for Xamarin Workbooks: export PATH="${DSTROOT}Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin'
fi
# before CodeMirror or Monaco we set these to disable all the magic
# stuff implied by the keys. CodeMirror, etc, handle preventing
# undesirable magic edits directly. Therefore, delete these keys
# to return to system defaults. -abock, 2016-07-20
for key in \
	WebAutomaticSpellingCorrectionEnabled \
	WebContinuousSpellCheckingEnabled \
	WebGrammarCheckingEnabled \
	WebSmartInsertDeleteEnabled \
	WebAutomaticQuoteSubstitutionEnabled \
	WebAutomaticDashSubstitutionEnabled \
	WebAutomaticLinkDetectionEnabled \
	WebAutomaticTextReplacementEnabled; do
	defaults delete com.xamarin.Inspector $key || true
done
