#!/bin/bash

if [ ! -d "${DSTROOT}" ]; then
	echo "DSTROOT is unset or is not a directory" 1>&2
	exit 1
fi

set -ex

function prepare_for_upgrade {
	rm -rf "${DSTROOT}${1}" || true
}

# Remove legacy paths
prepare_for_upgrade "Applications/Xamarin Inspector.app"
prepare_for_upgrade "Library/Frameworks/Xamarin.Inspector.framework"

interactive_framework_path="Library/Frameworks/Xamarin.Interactive.framework/Versions/Current"
uninstall_script="${DSTROOT}${interactive_framework_path}/uninstall"

# Run the previous installation's uninstaller if it exists,
# otherwise just remove the framework path
if [ -x "${uninstall_script}" ]; then
	"${uninstall_script}" -f
else
	prepare_for_upgrade "${interactive_framework_path}"
fi
