#!/bin/bash

set -ex

LEGACY_XS_ADDIN_INSTALL="${DSTROOT}${HOME#/*}/Library/Application Support/XamarinStudio-6.0/LocalInstall/Addins"
rm -rf "$LEGACY_XS_ADDIN_INSTALL/Xamarin.Inspector"
rm -rf "$LEGACY_XS_ADDIN_INSTALL/Xamarin.Interactive"

LEGACY_CLI_SCRIPT_PATH="${DSTROOT}usr/local/bin/workbook"
rm -f "$LEGACY_CLI_SCRIPT_PATH"

PATHS_D_PATH="/etc/paths.d/workbooks"
rm -f "$PATHS_D_PATH"
mkdir -p "$(dirname "$PATHS_D_PATH")"
{ cat <<EOF
${DSTROOT}Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
EOF
} > "$PATHS_D_PATH"

# before CodeMirror or Monaco we set these to disable all the magic
# stuff implied by the keys. CodeMirror, etc, handle preventing
# undesirable magic edits directly. Therefore, delete these keys
# to return to system defaults. -abock, 2016-07-20
for key in \
	WebAutomaticSpellingCorrectionEnabled \
	WebContinuousSpellCheckingEnabled \
	WebGrammarCheckingEnabled \
	WebSmartInsertDeleteEnabled \
	WebAutomaticQuoteSubstitutionEnabled \
	WebAutomaticDashSubstitutionEnabled \
	WebAutomaticLinkDetectionEnabled \
	WebAutomaticTextReplacementEnabled; do
	defaults delete com.xamarin.Inspector $key || true
done
